name: sunny_or_not
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_map: ^8.2.2
  fpdart: ^1.2.0
  geolocator: ^14.0.2
  get_it: ^9.2.1
  http: ^1.6.0
  latlong2: ^0.9.1
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc: ^9.2.0
  test: ^1.29.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
